site_name: Website Tracker
theme:
  name: material
  palette:
    primary: blue
    scheme: default
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - User Guide:
    - Getting Started: guide/getting-started.md
    - Configuration: guide/configuration.md
    - Monitoring Features: guide/monitoring.md
    - Change Detection: guide/change-detection.md
  - API Reference: 
    - Overview: api/index.md
    - Change Detection: api/change-detection.md
    - Timeline Visualization: api/timeline.md
  - Development:
    - Contributing: development/contributing.md
    - Architecture: development/architecture.md

repo_url: https://github.com/manicmeta1/website-tracker
repo_name: manicmeta1/website-tracker
edit_uri: edit/main/docs/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            show_source: true
            docstring_style: google