site_name: Website Tracker
theme:
  name: material
  palette:
    primary: blue
    scheme: default
nav:
  - Home: index.md
  - User Guide:
    - Getting Started: guide/getting-started.md
    - Configuration: guide/configuration.md
  - API Reference: api-reference.md
repo_url: https://github.com/manicmeta1/website-tracker
edit_uri: edit/main/docs/