name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdocstrings[python] pymdown-extensions
          pip install -r requirements.txt

      - name: Build documentation
        run: mkdocs build

      - name: Create documentation archive
        run: |
          cd site
          zip -r ../docs.zip .
          cd ..

      - name: Generate changelog
        id: changelog
        run: |
          # Get all commits since last tag
          previous_tag=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -z "$previous_tag" ]; then
            git log --pretty=format:"* %s%n" > CHANGELOG.md
          else
            git log ${previous_tag}..HEAD --pretty=format:"* %s%n" > CHANGELOG.md
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            docs.zip
            CHANGELOG.md
          generate_release_notes: true
          draft: false
          prerelease: false
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}